### ISSUE TITLE
Code duplication

### ISSUE THREAD

**Issue by ostrichby** [utscorpion/task-1#7]
Try to use the same makeDate() method for both Web and CLI mode.

https://github.com/utscorpion/task-1/blob/c7f57d2f33028da1d4e211db59d99bd0e9965fb6/php/functions.php#L27

**Comment by utscorpion** [comment]
If you don't mind i switch to Russian.
Эти фунции похожи, но по разному работают, из-за противоречия в задании и моего легкого несогласия с правильностью его: В тексте файла template.tpl написано, что мой первый день в Гетел ...., а далее в тех задании этот день должен быть текущим днем.
Я же для WEB сделал, что свой первый день ты должен выбрать в календаре, т.к. он один и не должен меняться. 
Потом, когда реализовывал CLI mode решил показать, что могу сделать и через функцию date(),
Но, прошу заметить, получать и обрабатывать данные с input type=date сложнее, и мне пришлось найти решение, из-за того, что с инпута приходит string.
Если это необходимо и важно, могу передеть на одну функции, в этом случае и web and cli дата будет формироваться или как текущая или установленаая вручную
Жду ОС)

**Comment by ostrichby** [comment]
Я тогда тоже перейду на русский)))
Даже в этом случае обе функции выполняют почти одно и то же и могут быть объединены.
Как насчет компромисса:
Пишем функцию, которая будет принимать на вход массив вида ['param' => 'value']. Если $arr['date'] пустой - запишем его из текущей даты.
В саму эту функцию мы будем передавать либо весь $_POST в веб режиме, либо будем формировать массив, если мы в CLI режиме вручную ['param1' => argv[1], 'param2' => argv[2]], при этом это нужно будет сделать всего один раз при вызове функции из index.php.
